name: Certinfo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: atsign-company/certinfo-action@v1

      - name: Get certinfo version
        run: certinfo --version
