on:
  workflow_dispatch:
    inputs:
      userinput:
        description: 'Type something here'
        required: true
        default: 'The quick brown fox jumps over the lazy dog!'

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      USER_INPUT: ${{ github.event.inputs.userinput }}
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${USER_INPUT}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}