on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      myenv: ${{ steps.addenv.outputs.myenv }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - id: addenv
        name: Add something to env
        run: |
          MYENV="1.2.3"
          echo "MYENV=$MYENV" >> $GITHUB_ENV
          echo "::set-output name=myenv::$MYENV"
      - name: Dump GitHub environment
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: |
          echo "$ENV_CONTEXT"
          echo "MYENV is $MYENV"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  two:
    needs: [one]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub environment
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: |
          echo "$ENV_CONTEXT"
          echo "MYENV is $MYENV"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job one myenv
        run: echo "Job one MYENV is ${{ needs.job1.outputs.myenv }}"
        

